### PR TITLE
Update readme for legacy customer

### PR DESCRIPTION
**Pull request by rehanjaved237-zz**

### CODE REVIEW

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-61-30d1946f`

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-61-e79872ab`

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-61-4543d06e`

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-61-d503054e`

**Review by ahmedwaleedmalik — APPROVED** [review]

**Pull request merged**
