### PR TITLE
Update Failing Pipeline

### PR DESCRIPTION
**Pull request by abdulhaseeb2**

### CODE REVIEW

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/d0ae89eff50dd8af91f916ae70e362f7fe2a21b1/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/c7bf7d1f6e311569ba5eeb73c9b71eb1652a3375/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/a9dbaac2356d7b0b30b83265364dc5079377d8c2/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/8410f6e7476d780a2d14fce0b5f4e41d045ef1d8/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/b12b547b4e7cf6758fe241a6d74ce53bb6a92860/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/26e939577ae7851be0d2fab9fb1b44141f6b3ab2/checks) has Failed!

**Review by ShahidHussain-srti — APPROVED** [review]

**Pull request merged**
