### PR TITLE
Add pipeline

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/ecf4fd38bf01314daa0b488e60de9f19cdd3c0cf/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/1dbf668372e42877fc1ee7b030dcf1b5e06f191e/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/38f77da1918ce76e598147dda03938b189e6a268/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-13-1b2c1834`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
