### PR TITLE
Update makefile

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-20-e782fd1d`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-20-b2c0cff9`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-20-f8274258`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-20-3700bdee`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-20-ce95eefd`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-20-0a81d124`

**Review by usamaahmadkhan — APPROVED** [review]

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-20-484b7373`

**Pull request merged**
