### PR TITLE
Update operator-sdk to v1.20.0

### PR DESCRIPTION
**Pull request by abdulhaseeb2**

### CODE REVIEW

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/560d2b0a5f6dc04f9750d69c78e202b577057659/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-87-eab44362`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-87-2ea5d474`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-87-839175a0`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-87-113cbe35`

**Review by MuneebAijaz — DISMISSED** [review]

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-87-e3548b00`

**Review by ShahidHussain-srti — APPROVED** [review]

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-87-b57b42cc`

**Pull request merged**
