### PR TITLE
Remove downloaded kubectl binary after installation in pipeline

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Review by kahootali — DISMISSED** [review]

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/f26ebbe65a21434de002044a05a59cd9516ef069/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/f26ebbe65a21434de002044a05a59cd9516ef069/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/f26ebbe65a21434de002044a05a59cd9516ef069/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/6a9228b4adb386e4a625afe38498a02eaf3073d9/checks) has Failed!

**Review by usamaahmadkhan — APPROVED** [review]

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-35-6a9228b4`

**Pull request merged**
