### PR TITLE
Add helm chart

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-48-2341ece5`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-48-3a75249a`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-48-cad244e8`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-48-05bd5c3f`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-48-48a8204c`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
