### PR TITLE
WIP: Handle create customer

### PR DESCRIPTION
**Pull request by rehanjaved237-zz**

### CODE REVIEW

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-28-ef641013`

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/ab9ef3abe6c8740c5658a2f52903fc788c48978b/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/a9a301b5d22b2c57ee8a1367aed5abd755c5cf03/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/f18337ea057e0bd1568431db777aae3e283caace/checks) has Failed!

**Comment by ahmedwaleedmalik** [comment]
Done in #31

**Pull request closed without merging**
