### PR TITLE
Update chart and pipelines

### PR DESCRIPTION
**Pull request by abdulhaseeb2**

### CODE REVIEW

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/e0735d1dbd38a22714bdba1eceb99e2802a23aaf/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/a188d09821e80f0029dc896c9898276089884afc/checks) has Failed!

**Comment by stakater-user** [comment]
@LilShah Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/a188d09821e80f0029dc896c9898276089884afc/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/c287acb3d0a090b8f3d3016233b37b8f5dcc1432/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/d6d5b53b83eb8e2227716601758909ba2a3af558/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/2ad8ce1ffa3c609aa94aac2c7681ae18a123f2d1/checks) has Failed!

**Review by tanalam2411 — APPROVED** [review]

**Pull request merged**
