### PR TITLE
Fix customer tests

### PR DESCRIPTION
**Pull request by rehanjaved237-zz**

### CODE REVIEW

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/202d5480160e8cfe1efac27f00b5c8943ae0189e/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/bead92f66d0d681fa3da2431f33da0a8b41e1463/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/d082ba603ffe475c5d24c024b725ae8d9382675f/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/9131f8d28c8aff4a43c4bb19f31a082f31ce02b8/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/52fa545df21ede623cd09589394d9dd3c6db07fb/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/c7ac015794673b81f87098f542d3b78485462bc0/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/a277b45e9ea8d499f82aa00096b7316ecde8324c/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/840b73839f5cdd7c1c1df89296d61b4b44ebcfa0/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-70-840b7383`

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/c872bcfdbca0ca8488c204f919560fb6f0364515/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-70-c872bcfd`

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/1310d90e73c4163b1e45fb7bfa0307a525aaf928/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-70-d69deaac`

**Review by ahmedwaleedmalik — APPROVED** [review]

**Pull request merged**
